name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]        

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Build Linux Client
        run: nix build .#hydrangea-client-linux

      - name: Upload Linux Client Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydrangea-client-linux
          path: result

      - name: Build Windows Client
        run: nix build .#hydrangea-client-windows

      - name: Upload Windows Client Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hydrangea-client-windows
          path: result
